version: "3.8"

services:

  frontend:
    build: ./frontend
    container_name: react_frontend
    ports:
      - 3000:3000
    stdin_open: true
    tty : true


  backend:
    build: ./backend
    container_name: fastapi
    
    ports:
      - 8000:80
    
    restart: "no"